# Generated by Django 3.2.8 on 2021-12-12 14:05

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('project_image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='project_image')),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('prof_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='awards.profile')),
            ],
        ),
    ]
