# Generated by Django 3.2.8 on 2021-12-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['pub_date']},
        ),
    ]
